[package]
name = "rattler_tuf"
version.workspace = true
edition.workspace = true
authors = ["Wolf Vollprecht <wolf@prefix.dev>"]
description = "A crate to verify trust for conda repositories"
categories.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
chrono = { version = "0.4.31", features = ["serde"] }
ed25519-dalek = { version = "2.0.0", features = ["serde"] }
hex = "0.4.3"
serde = { version = "1.0.192", features = ["derive", "std"] }
serde_json = "1.0.108"
sha2 = "0.10.8"

[dev-dependencies]
insta = "1.34.0"
