[package]
name = "rattler_networking"
version.workspace = true
edition.workspace = true
authors = ["Wolf Vollprecht <w.vollprecht@gmail.com>"]
description = "Authenticated requests in the conda ecosystem"
categories.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[features]
default = ['blocking']
native-tls = ['reqwest/native-tls']
rustls-tls = ['reqwest/rustls-tls']
blocking = ['reqwest/blocking']

[dependencies]
anyhow = "1.0.75"
dirs = "5.0.1"
fslock = "0.2.1"
itertools = "0.12.0"
keyring = "2.1.0"
lazy_static = "1.4.0"
libc = "0.2.151"
once_cell = "1.19.0"
reqwest = { version = "0.11.22", default-features = false }
retry-policies = { version = "0.2.1", default-features = false }
serde = "1.0.193"
serde_json = "1.0.108"
thiserror = "1.0.50"
tracing = "0.1.40"
url = "2.5.0"

[target.'cfg( target_arch = "wasm32" )'.dependencies]
getrandom = { version = "0.2.11", features = ["js"] }

[dev-dependencies]
anyhow = "1.0.75"
insta = { version = "1.34.0", features = ["json"] }
tempfile = "3.8.1"
