[package]
name = "rattler_networking"
version.workspace = true
edition.workspace = true
authors = ["Wolf Vollprecht <w.vollprecht@gmail.com>"]
description = "Authenticated requests in the conda ecosystem"
categories.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
keyring = "2.0.2"
reqwest = {version = "0.11.17", features = ["blocking"]}
thiserror = "1.0.40"
tracing = "0.1.37"

[dev-dependencies]
