[workspace]
members = ["crates/*"]
resolver = "2"

# See: https://docs.rs/insta/latest/insta/#optional-faster-runs
[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3

[workspace.package]
version = "0.17.0"
categories = ["conda"]
homepage = "https://github.com/mamba-org/rattler"
repository = "https://github.com/mamba-org/rattler"
license = "BSD-3-Clause"
edition = "2021"
readme = "README.md"

[workspace.metadata.release]
allow-branch = ["main"]
consolidate-commits = true
tag-prefix = ""

[profile.bench]
lto = true

[workspace.dependencies]
anyhow = "1.0.79"
assert_matches = "1.5.0"
async-compression = { version = "0.4.6", features = ["gzip", "tokio", "bzip2", "zstd"] }
async-trait = "0.1.77"
async_zip = { version = "0.0.16", default-features = false }
axum = { version = "0.7.4", default-features = false, features = ["tokio", "http1"] }
base64 = "0.21.7"
bindgen = "0.66.1"
bisection = "0.1.0"
blake2 = "0.10.6"
bytes = "1.5.0"
bzip2 = "0.4.4"
cache_control = "0.2.0"
cfg-if = "1.0"
chrono = { version = "0.4.33", default-features = false, features = ["std", "serde", "alloc"] }
clap = { version = "4.4.18", features = ["derive"] }
cmake = "0.1.50"
console = { version = "0.15.8", features = ["windows-console-colors"] }
criterion = "0.5"
difference = "2.0.0"
digest = "0.10.7"
dirs = "5.0.1"
drop_bomb = "0.1.5"
dunce = "1.0.4"
enum_dispatch = "0.3.12"
fs-err = "2.11.0"
fslock = "0.2.1"
futures = "0.3.30"
futures-util = "0.3.30"
fxhash = "0.2.1"
getrandom = { version = "0.2.12", default-features = false }
glob = "0.3.1"
hex = "0.4.3"
hex-literal = "0.4.1"
http-content-range = "0.1.2"
humansize = "2.1.3"
humantime = "2.1.0"
indexmap = "2.2.2"
indicatif = "0.17.7"
insta = { version = "1.34.0" }
itertools = "0.12.1"
json-patch = "1.2.0"
keyring = "2.3.2"
lazy-regex = "3.1.0"
lazy_static = "1.4.0"
libc = { version = "0.2" }
libloading = "0.8.1"
libz-sys = { version = "1.1.15", default-features = false }
md-5 = "0.10.6"
memchr = "2.7.1"
memmap2 = "0.9.4"
netrc-rs = "0.1.2"
nom = "7.1.3"
num_cpus = "1.16.0"
once_cell = "1.19.0"
ouroboros = "0.18.3"
pathdiff = "0.2.1"
pep440_rs = { version = "0.4.0" }
pep508_rs = { version = "0.3.0" }
pin-project-lite = "0.2.13"
plist = "1"
purl = { version = "0.1.2", features = ["serde"] }
quote = "1.0.35"
rand = "0.8.5"
rattler = { version = "0.17.0", path = "crates/rattler", default-features = false }
rattler_conda_types = { version = "0.17.0", path = "crates/rattler_conda_types", default-features = false }
rattler_digest = { version = "0.17.0", path = "crates/rattler_digest", default-features = false }
rattler_libsolv_c = { version = "0.17.0", path = "crates/rattler_libsolv_c", default-features = false }
rattler_lock = { version = "0.17.0", path = "crates/rattler_lock" }
rattler_macros = { version = "0.17.0", path = "crates/rattler_macros", default-features = false }
rattler_networking = { version = "0.17.0", path = "crates/rattler_networking", default-features = false }
rattler_package_streaming = { version = "0.17.0", path = "crates/rattler_package_streaming", default-features = false }
rattler_repodata_gateway = { version = "0.17.0", path = "crates/rattler_repodata_gateway", default-features = false }
rattler_solve = { version = "0.17.0", path = "crates/rattler_solve", default-features = false }
rattler_virtual_packages = { version = "0.17.0", path = "crates/rattler_virtual_packages", default-features = false }
reflink-copy = "0.1.14"
regex = "1.10.3"
reqwest = { version = "0.11.24", default-features = false }
reqwest-middleware = "0.2.4"
resolvo = { version = "0.3.0" }
retry-policies = { version = "0.2.1", default-features = false }
rstest = { version = "0.18.2" }
rstest_reuse = "0.6.0"
serde = { version = "1.0.196" }
serde-json-python-formatter = "0.1.0"
serde_json = { version = "1.0.113" }
serde_repr = "0.1"
serde_with = "3.6.0"
serde_yaml = "0.9.31"
sha2 = "0.10.8"
shlex = "1.3.0"
similar-asserts = "1.5.0"
smallvec = { version = "1.13.1", features = ["serde", "const_new", "const_generics", "union"] }
strum = { version = "0.26.1", features = ["derive"] }
superslice = "1.0.0"
syn = "2.0.48"
sysinfo = "0.30.5"
tar = "0.4.40"
task-local-extensions = "0.1.4"
tempdir = "0.3.7"
tempfile = "3.9.0"
test-log = "0.2.14"
thiserror = "1.0"
tokio = { version = "1.35.1", default-features = false }
tokio-stream = "0.1.14"
tokio-util = "0.7.10"
tower = { version = "0.4.13", default-features = false }
tower-http = { version = "0.5.1", default-features = false }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", default-features = false }
tracing-test = { version = "0.2.4" }
trybuild = { version = "1.0.89" }
url = { version = "2.5.0" }
uuid = { version = "1.7.0", default-features = false }
walkdir = "2.4.0"
windows-sys = { version = "0.52.0", default-features = false }
zip = { version = "0.6.6", default-features = false }
zstd = { version = "0.13.0", default-features = false }

[patch.crates-io]
resolvo = { git = "https://github.com/aochagavia/resolvo.git", branch = "concurrent-metadata-fetching" }
