[package]
name = "rattler_macros"
version.workspace = true
edition.workspace = true
authors = ["Wolf Vollprecht <w.vollprecht@gmail.com>"]
description = "A crate that provideds some procedural macros for the rattler project"
categories.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true
autotests = false

[lib]
proc-macro = true

[[test]]
name = "tests"
path = "tests/tests.rs"

[dependencies]
syn = "2.0.37"
quote = "1.0.33"

[dev-dependencies]
trybuild = { version = "1.0.85", features = ["diff"] }
