recipe:
  name: clobber
  version: 0.1.0

outputs:
  - package:
      name: clobber-1
      version: 0.1.0
    
    build:  
      noarch: generic
      script:
        - echo "clobber-1" > $PREFIX/clobber.txt

  - package:
      name: clobber-2
      version: 0.1.0
    
    build:  
      noarch: generic
      script:
        - echo "clobber-2" > $PREFIX/clobber.txt

  - package:
      name: clobber-3
      version: 0.1.0
    
    build:  
      noarch: generic
      script:
        - echo "clobber-3" > $PREFIX/clobber.txt
