[package]
name = "tools"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
bindgen = { workspace = true }
clap = { workspace = true, features = ["derive"] }
difference = { workspace = true }
tempdir = { workspace = true }

[package.metadata.release]
# Dont publish the binary
release = false
