[package]
name = "rattler_conda_types"
version.workspace = true
edition.workspace = true
authors = ["Bas Zalmstra <zalmstra.bas@gmail.com>"]
description = "Rust data types for common types used within the Conda ecosystem"
categories.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
chrono = "0.4.31"
fxhash = "0.2.1"
hex = "0.4.3"
indexmap = { version = "2.1.0", features = ["serde"] }
itertools = "0.11.0"
lazy-regex = "3.1.0"
nom = "7.1.3"
regex = "1.10.2"
serde = { version = "1.0.193", features = ["derive", "rc"] }
serde_json = "1.0.108"
serde_yaml = "0.9.27"
serde_with = { version = "3.4.0", features = ["indexmap_2"] }
serde_repr = "0.1"
smallvec = { version = "1.11.2", features = ["serde", "const_new", "const_generics", "union"] }
strum = { version = "0.25.0", features = ["derive"] }
thiserror = "1.0.50"
tracing = "0.1.40"
url = { version = "2.5.0", features = ["serde"] }
rattler_digest = { version = "0.14.0", path = "../rattler_digest", features = ["serde"] }
rattler_macros = { version = "0.14.0", path = "../rattler_macros" }
glob = "0.3.1"
purl = { version = "0.1.2", features = ["serde"] }

[dev-dependencies]
rand = "0.8.5"
insta = { version = "1.34.0", features = ["yaml", "redactions", "toml"] }
rattler_package_streaming = { path = "../rattler_package_streaming", default-features = false, features = ["rustls-tls"] }
tempfile = "3.8.1"
rstest = "0.18.2"
assert_matches = "1.5.0"
hex-literal = "0.4.1"
criterion = { version = "0.5", features = ["html_reports"] }
pathdiff = "0.2.1"
dunce = "1.0.4"

[[bench]]
name = "parse"
harness = false
