site_name: "py-rattler"

theme:
  name: material

repo_url: https://github.com/mamba-org/rattler/

nav:
  - Home: index.md
  - References:
      - channel:
          - ChannelConfig: channel_config.md
          - Channel: channel.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false

  - search
