site_name: "py-rattler"

theme:
  name: "readthedocs"

repo_url: https://github.com/mamba-org/rattler/

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false

  - search
