[package]
name = "rattler-bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "rattler"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.44"
clap = { version="4.0.8", features=["derive"] }
dirs = "4.0.0"
rattler = { path="../rattler" }
tokio = { version = "1.21.1", features=["rt-multi-thread", "macros"]}
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
