[package]
name = "rattler-bin"
version.workspace = true
edition.workspace = true
authors = ["Bas Zalmstra <zalmstra.bas@gmail.com>"]
description = "Rust binary for common Conda operations"
categories.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true
default-run = "rattler"

[[bin]]
name = "rattler"
path = "src/main.rs"

[features]
default = ["native-tls"]
native-tls = ["reqwest/native-tls", "rattler/native-tls", "rattler_repodata_gateway/native-tls", "rattler_networking/native-tls"]
rustls-tls = ["reqwest/rustls-tls", "rattler/rustls-tls", "rattler_repodata_gateway/rustls-tls", "rattler_networking/rustls-tls"]

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
console = { workspace = true, features = ["windows-console-colors"] }
dirs = { workspace = true }
futures = { workspace = true }
indicatif = { workspace = true }
itertools = { workspace = true }
once_cell = { workspace = true }
rattler = { workspace = true }
rattler_conda_types = { workspace = true }
rattler_networking = { workspace = true }
rattler_repodata_gateway = { workspace = true, features = ["sparse"] }
rattler_solve = { workspace = true, features = ["resolvo", "libsolv_c"] }
rattler_virtual_packages = { workspace = true }
reqwest = { workspace = true }
reqwest-middleware = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }

[package.metadata.release]
# Dont publish the binary
release = false
