[package]
name = "rattler-bin"
version = "0.1.0"
edition = "2021"
authors = ["Bas Zalmstra <zalmstra.bas@gmail.com>"]
description = "Rust binary for common Conda operations"
categories = ["conda"]
homepage = "https://github.com/baszalmstra/rattler"
repository = "https://github.com/baszalmstra/rattler"
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "rattler"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.44"
clap = { version="4.0.13", features=["derive"] }
dirs = "4.0.0"
rattler = { path="../rattler" }
tokio = { version = "1.21.1", features=["rt-multi-thread", "macros"]}
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
rattler_conda_types = { version = "0.1.0", path = "../rattler_conda_types" }
