[package]
name = "rattler_package_streaming"
version.workspace = true
edition.workspace = true
authors = ["Bas Zalmstra <zalmstra.bas@gmail.com>"]
description = "Extract and stream of Conda package archives"
categories.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
bzip2 = "0.4.4"
chrono = "0.4.31"
futures-util = { version = "0.3.28", optional = true }
itertools = "0.11.0"
rattler_conda_types = { version = "0.10.0", path = "../rattler_conda_types" }
rattler_digest = { version = "0.10.0", path = "../rattler_digest" }
serde_json = "1.0.107"
tar = { version = "0.4.40" }
thiserror = "1.0.49"
tokio = { version = "1", optional = true }
tokio-util = { version = "0.7", optional = true }
reqwest = { version = "0.11.22", optional = true, default-features = false }
url = "2.4.1"
zip = { version = "0.6.6", default-features = false, features = ["deflate", "time"] }
zstd = { version = "0.12.4", default-features = false }
rattler_networking = { version = "0.10.0", path = "../rattler_networking", default-features = false }

[features]
default = ["native-tls", "blocking"]
tokio = ["dep:tokio", "bzip2/tokio", "tokio/fs", "tokio-util/io", "tokio-util/io-util", "reqwest?/stream", "futures-util"]
native-tls = ["rattler_networking/native-tls"]
rustls-tls = ["rattler_networking/rustls-tls"]
blocking = ["rattler_networking/blocking"]
wasm = ["zstd/wasm"]

[dev-dependencies]
tempfile = "3.8.0"
tokio = { version = "1", features = ["rt", "macros"] }
walkdir = "2.4.0"
rstest = "0.18.2"
rstest_reuse = "0.6.0"
