[package]
name = "rattler_package_streaming"
version.workspace = true
edition.workspace = true
authors = ["Bas Zalmstra <zalmstra.bas@gmail.com>"]
description = "Extract and stream of Conda package archives"
categories.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
bzip2 = { version = "0.4" }
chrono = "0.4.26"
futures-util = { version = "0.3.28", optional = true }
itertools = "0.10.5"
rattler_conda_types = { version = "0.2.0", path = "../rattler_conda_types" }
rattler_digest = { version = "0.2.0", path = "../rattler_digest" }
serde_json = "1.0.96"
tar = { version = "0.4.38" }
thiserror = "1.0.40"
tokio = { version = "1", optional = true }
tokio-util = { version = "0.7", optional = true }
reqwest = { version = "0.11.18", optional = true, default-features = false }
url = "2.4.0"
zip = { version = "0.6.6" }
zstd = "0.12.3"
rattler_auth = { version = "0.2.0", path = "../rattler_auth" }

[features]
default = ['native-tls']
tokio = ["dep:tokio", "bzip2/tokio", "tokio/fs", "tokio-util/io", "tokio-util/io-util", "reqwest?/stream", "futures-util"]
native-tls = ['reqwest?/native-tls']
rustls-tls = ['reqwest?/rustls-tls']
reqwest = ["reqwest/blocking"]

[dev-dependencies]
tempfile = "3.6.0"
tokio = { version = "1", features = ["rt", "macros"] }
walkdir = "2.3.3"
rstest = "0.17.0"
rstest_reuse = "0.5.0"
