[package]
name = "rattler_repodata_gateway"
version.workspace = true
edition.workspace = true
authors = ["Bas Zalmstra <zalmstra.bas@gmail.com>"]
description = "A crate to interact with Conda repodata"
categories.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
async-compression = { version = "0.4.0", features = ["gzip", "tokio", "bzip2", "zstd"] }
blake2 = "0.10.6"
cache_control = "0.2.0"
chrono = { version = "0.4.26", default-features = false, features = ["std", "serde", "alloc", "clock"] }
humansize = "2.1.3"
humantime = "2.1.0"
futures = "0.3.28"
reqwest = { version = "0.11.18", default-features = false, features = ["stream"] }
tokio-util = { version = "0.7.8", features = ["codec", "io"] }
tempfile = "3.6.0"
tracing = "0.1.37"
thiserror = "1.0.40"
url = { version = "2.4.0", features = ["serde"] }
tokio = { version = "1.28.2", features = ["rt", "io-util"] }
anyhow = "1.0.71"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = { version = "1.0.96" }
pin-project-lite = "0.2.9"
md-5 = "0.10.5"
rattler_digest = { version = "0.2.0", path = "../rattler_digest", features = ["tokio", "serde"] }
rattler_conda_types = { version = "0.2.0", path = "../rattler_conda_types", optional = true }
fxhash = { version = "0.2.1", optional = true }
memmap2 = { version = "0.6.2", optional = true }
ouroboros = { version = "0.15.6", optional = true }
serde_with = "3.0.0"
superslice = { version = "1.0.0", optional = true }
itertools = { version = "0.10.5", optional = true }
json-patch = "1.0.0"
hex = { version = "0.4.3", features = ["serde"] }
rattler_networking = { version = "0.2.0", path = "../rattler_networking", default-features = false }

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.48.0", features = ["Win32_Storage_FileSystem", "Win32_Foundation", "Win32_System_IO"] }

[dev-dependencies]
hex-literal = "0.4.1"
tower-http = { version = "0.4.0", features = ["fs", "compression-gzip", "trace"] }
tracing-test = { version = "0.2.4" }
insta = { version = "1.29.0", features = ["yaml"] }
axum = "0.6.18"
assert_matches = "1.5.0"
tokio = { version = "1.28.2", features = ["macros", "rt-multi-thread"] }
rstest = "0.17.0"

[features]
default = ['native-tls']
native-tls = ['reqwest/native-tls']
rustls-tls = ['reqwest/rustls-tls']
sparse = ["rattler_conda_types", "memmap2", "ouroboros",  "superslice", "itertools", "serde_json/raw_value"]
