[package]
name = "rattler"
version.workspace = true
edition.workspace = true
authors = ["Bas Zalmstra <zalmstra.bas@gmail.com>"]
description = "Rust library to install conda environments"
categories.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[features]
default = ['native-tls']
native-tls = ['reqwest/native-tls', 'rattler_package_streaming/native-tls']
rustls-tls = ['reqwest/rustls-tls', 'rattler_package_streaming/rustls-tls']

[dependencies]
anyhow = "1.0.71"
async-compression = { version = "0.4.1", features = ["gzip", "tokio", "bzip2", "zstd"] }
bytes = "1.4.0"
chrono = { version = "0.4.26", default-features = false, features = ["std", "serde", "alloc"] }
digest = "0.10.7"
dirs = "5.0.1"
futures = "0.3.28"
fxhash = "0.2.1"
hex = "0.4.3"
itertools = "0.11.0"
memchr = "2.5.0"
memmap2 = "0.7.1"
nom = "7.1.3"
once_cell = "1.18.0"
pin-project-lite = "0.2.10"
rattler_conda_types = { version = "0.5.0", path = "../rattler_conda_types" }
rattler_digest = { version = "0.5.0", path = "../rattler_digest" }
rattler_networking = { version = "0.5.0", path = "../rattler_networking", default-features = false }
rattler_package_streaming = { version = "0.5.0", path = "../rattler_package_streaming", features = ["reqwest", "tokio"], default-features = false }
regex = "1.9.1"
reqwest = { version = "0.11.18", default-features = false, features = ["stream", "json", "gzip"] }
serde = { version = "1.0.171", features = ["derive"] }
serde_json = { version = "1.0.102", features = ["raw_value"] }
serde_with = "3.0.0"
smallvec = { version = "1.11.0", features = ["serde", "const_new", "const_generics", "union"] }
tempfile = "3.6.0"
thiserror = "1.0.43"
tokio = { version = "1.29.1", features = ["rt", "io-util", "macros"] }
tokio-stream = "0.1.14"
tokio-util = { version = "0.7.8", features = ["codec", "io"] }
tracing = "0.1.37"
url = { version = "2.4.0", features = ["serde"] }
uuid = { version = "1.4.0", features = ["v4", "fast-rng"] }

[dev-dependencies]
assert_matches = "1.5.0"
rand = "0.8.5"
rstest = "0.18.1"
tracing-test = { version = "0.2.4" }
insta = { version = "1.30.0", features = ["yaml"] }
