[package]
name = "rattler"
version.workspace = true
edition.workspace = true
authors = ["Bas Zalmstra <zalmstra.bas@gmail.com>"]
description = "Rust library to install conda environments"
categories.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[features]
default = ['native-tls']
native-tls = ['reqwest/native-tls', 'rattler_package_streaming/native-tls']
rustls-tls = ['reqwest/rustls-tls', 'rattler_package_streaming/rustls-tls']

[dependencies]
anyhow = "1.0.71"
apple-codesign = "0.22.0"
async-compression = { version = "0.4.0", features = ["gzip", "tokio", "bzip2", "zstd"] }
bytes = "1.4.0"
chrono = { version = "0.4.26", default-features = false, features = ["std", "serde", "alloc"] }
digest = "0.10.7"
dirs = "5.0.1"
futures = "0.3.28"
fxhash = "0.2.1"
hex = "0.4.3"
itertools = "0.10.5"
memchr = "2.5.0"
memmap2 = "0.6.2"
nom = "7.1.3"
once_cell = "1.18.0"
pin-project-lite = "0.2.9"
rattler_conda_types = { version = "0.2.0", path = "../rattler_conda_types" }
rattler_digest = { version = "0.2.0", path = "../rattler_digest" }
rattler_package_streaming = { version = "0.2.0", path = "../rattler_package_streaming", features = ["reqwest", "tokio"], default-features = false }
regex = "1.8.4"
reqwest = { version = "0.11.18", default-features = false, features = ["stream", "json", "gzip"] }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = { version = "1.0.96", features = ["raw_value"] }
serde_with = "3.0.0"
smallvec = { version = "1.10.0", features = ["serde", "const_new", "const_generics", "union"] }
tempfile = "3.6.0"
thiserror = "1.0.40"
tokio = { version = "1.28.2", features = ["rt", "io-util", "macros"] }
tokio-stream = "0.1.14"
tokio-util = { version = "0.7.8", features = ["codec", "io"] }
tracing = "0.1.37"
url = { version = "2.4.0", features = ["serde"] }
uuid = { version = "1.3.3", features = ["v4", "fast-rng"] }

[dev-dependencies]
assert_matches = "1.5.0"
rand = "0.8.5"
rstest = "0.17.0"
tracing-test = { version = "0.2.4" }
insta = { version = "1.29.0", features = ["yaml"] }
