[package]
name = "rattler"
version.workspace = true
edition.workspace = true
authors = ["Bas Zalmstra <zalmstra.bas@gmail.com>"]
description = "Rust library to install conda environments"
categories.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[features]
default = ['native-tls']
native-tls = ['reqwest/native-tls', 'rattler_package_streaming/native-tls']
rustls-tls = ['reqwest/rustls-tls', 'rattler_package_streaming/rustls-tls']

[dependencies]
anyhow = "1.0.44"
apple-codesign = "0.22.0"
async-compression = { version = "0.3.12", features = ["gzip", "tokio", "bzip2", "zstd"] }
bytes = "1.1.0"
chrono = { version = "0.4.23", default-features = false, features = ["std", "serde", "alloc"] }
digest = "0.10.6"
dirs = "5.0.0"
futures = "0.3.17"
fxhash = "0.2.1"
hex = "0.4.3"
itertools = "0.10.3"
memchr = "2.5.0"
memmap2 = "0.5.8"
nom = "7.1.0"
once_cell = "1.8.0"
pin-project-lite = "0.2.9"
rattler_conda_types = { version = "0.2.0", path = "../rattler_conda_types" }
rattler_digest = { version = "0.2.0", path = "../rattler_digest" }
rattler_package_streaming = { version = "0.2.0", path = "../rattler_package_streaming", features = ["reqwest", "tokio"] }
regex = "1.5.4"
reqwest = { version = "0.11.6", default-features = false, features = ["stream", "json", "gzip"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = { version = "1.0.68", features = ["raw_value"] }
serde_with = "2.0.0"
smallvec = { version = "1.8.0", features = ["serde", "const_new", "const_generics", "union"] }
tempfile = "3.3.0"
thiserror = "1.0.30"
tokio = { version = "1.12.0", features = ["rt", "io-util", "macros"] }
tokio-stream = "0.1.11"
tokio-util = { version = "0.7.3", features = ["codec", "io"] }
tracing = "0.1.29"
url = { version = "2.2.2", features = ["serde"] }
uuid = { version = "1.3.0", features = ["v4", "fast-rng"] }

[dev-dependencies]
assert_matches = "1.5.0"
rand = "0.8.4"
rstest = "0.17.0"
tracing-test = { version = "0.2.4" }
insta = { version = "1.16.0", features = ["yaml"] }
