[package]
name = "rattler"
version.workspace = true
edition.workspace = true
authors = ["Bas Zalmstra <zalmstra.bas@gmail.com>"]
description = "Rust library to install conda environments"
categories.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[features]
default = ['native-tls']
native-tls = ['reqwest/native-tls', 'rattler_package_streaming/native-tls']
rustls-tls = ['reqwest/rustls-tls', 'rattler_package_streaming/rustls-tls']

[dependencies]
anyhow = "1.0.75"
async-compression = { version = "0.4.5", features = ["gzip", "tokio", "bzip2", "zstd"] }
bytes = "1.5.0"
chrono = { version = "0.4.31", default-features = false, features = ["std", "serde", "alloc"] }
digest = "0.10.7"
dirs = "5.0.1"
futures = "0.3.29"
fxhash = "0.2.1"
hex = "0.4.3"
itertools = "0.11.0"
memchr = "2.6.4"
memmap2 = "0.7.1"
nom = "7.1.3"
once_cell = "1.19.0"
pin-project-lite = "0.2.13"
rattler_conda_types = { version = "0.14.0", path = "../rattler_conda_types" }
rattler_digest = { version = "0.14.0", path = "../rattler_digest" }
rattler_networking = { version = "0.14.0", path = "../rattler_networking", default-features = false }
rattler_package_streaming = { version = "0.14.0", path = "../rattler_package_streaming", features = ["reqwest", "tokio"], default-features = false }
regex = "1.10.2"
reqwest = { version = "0.11.22", default-features = false, features = ["stream", "json", "gzip"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = { version = "1.0.108", features = ["raw_value"] }
serde_with = "3.4.0"
smallvec = { version = "1.11.2", features = ["serde", "const_new", "const_generics", "union"] }
tempfile = "3.8.1"
thiserror = "1.0.50"
tokio = { version = "1.35.0", features = ["rt", "io-util", "macros"] }
tokio-stream = "0.1.14"
tokio-util = { version = "0.7.10", features = ["codec", "io"] }
tracing = "0.1.40"
url = { version = "2.5.0", features = ["serde"] }
uuid = { version = "1.6.1", features = ["v4", "fast-rng"] }

[dev-dependencies]
assert_matches = "1.5.0"
rand = "0.8.5"
rstest = "0.18.2"
tracing-test = { version = "0.2.4" }
insta = { version = "1.34.0", features = ["yaml"] }
rattler_lock = { path="../rattler_lock"}

tokio = { version = "1.35.0", features = ["macros", "rt-multi-thread"] }
axum = "0.6.20"
tower-http = { version = "0.4.4", features = ["fs"] }
tower = { version = "0.4.13", default-features = false, features = ["util"] }
