name: Python bindings CI

on:
  push:
    branches: [ $default-branch ]
    paths:
      - 'py-rattler/**/*'
      - '.github/workflows/python-bindings.yml'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  format_lint_test:
    name: Format, Lint and Test the Python bindings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: |
          curl -fsSL https://pixi.sh/install.sh | bash
          echo "/home/runner/.pixi/bin" >> $GITHUB_PATH
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
      - name: Format and Lint
        run: |
          cd py-rattler
          pixi run lint
          pixi run fmt-check
      - name: Run tests
        run: |
          cd py-rattler
          pixi run test
