name: Python bindings CI

on:
  push:
    branches: [ main ]
    paths:
      - 'py-rattler/**/*'
      - '.github/workflows/python-bindings.yml'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  format_lint_test:
    name: Format, Lint and Test the Python bindings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: true
      - uses: prefix-dev/setup-pixi@v0.5.1
        with:
          pixi-version: v0.10.0
          cache: true
          manifest-path: py-rattler/pixi.toml
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
      - name: Format and Lint
        run: |
          cd py-rattler
          pixi run lint
          pixi run fmt-check
      - name: Run tests
        run: |
          cd py-rattler
          pixi run test
